### ISSUE TITLE
Доработки и баги

### ISSUE THREAD

**Issue by woobla** [evgen3/mpa-frontend-template#27]
- нельзя подключать иконки с папки ico (через css)
- нельзя подключать изображения в html через style
- и обновление страницы при изменениях не удобно работает и немного усложняет верстку, страница полностью обновляется как если бы я нажал кнопочку

и добавь те доработки что в проекте сделал...

**Comment by zhenkuzne** [comment]
>нельзя подключать иконки с папки ico (через css)

папка /ico предназначена для подключения иконок в разметку
если хочешь в стилях, используй /img и как обычно

>нельзя подключать изображения в html через style

добавил инструкцию в readme

>и обновление страницы при изменениях не удобно работает и немного усложняет верстку, страница полностью обновляется как если бы я нажал кнопочку

да, это печально, пока решений нет
